easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Contribution
        - App\Entity\Project
        - App\Entity\Category
        - App\Entity\User
